backend:
  name: github
  repo: WebWeWant/webwewant.fyi
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Wants
  - name: "wants"
    label: "Want"
    folder: "wants"
    create: true
    slug: "{{number}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Submission Date", name: "date", widget: "datetime" }
      - { label: "Submitted By", name: "submitter", widget: "string" }
      - { label: "Number", name: "number", widget: "number" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "body", widget: "markdown" }
  # Pages
  - name: "pages"
    label: "Page"
    folder: "pages"
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Navigation Title", name: "navtitle", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "nav" }
      - { label: "Body", name: "body", widget: "markdown" }
  # Events
  - name: "data"
    label: "Data Files"
    files:
      - label: "Events"
        name: "events"
        file: "_data/events.json"
        delete: false
        fields:
          - label: "Event List"
            name: "items"
            widget: "list"
            fields:
              - { label: "Event Name", name: "title", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Location", name: "location", widget: "string" }
              - { label: "Start Date", name: "start_date", widget: "datetime" }
              - { label: "End Date", name: "end_date", widget: "datetime" }
              - { label: "IANA Time Zone", name: "zone", widget: "string" }
